### ISSUE TITLE
ubuntu-ui-toolkit-git patch fails

### ISSUE THREAD

**Issue by Austcool-Walker** [vanyasem/Unity8-Arch#5] opened 2019-02-12 23:00 UTC
```[noire@Austcools-MacBook-Pro ubuntu-ui-toolkit-git]$ makepkg
==> Making package: ubuntu-ui-toolkit-git r17954.de9a0b250-2 (Tue 12 Feb 2019 05:55:17 PM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning ubuntu-ui-toolkit git repo...
Cloning into bare repository '/home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/ubuntu-ui-toolkit'...
remote: Enumerating objects: 259, done.
remote: Counting objects: 100% (259/259), done.
remote: Compressing objects: 100% (183/183), done.
Receiving objects:   0% (865/141211), 108.01 KiB | 151.00 Receiving objects:   1% (1413/141211), 220.01 KiB | 180.00Receiving objects:   1% (1636/141211), 308.01 KiB | 177.00Receiving objects:   2% (2825/141211), 412.01 KiB | 184.00Receiving objects:   2% (3296/141211), 628.01 KiB | 229.00Receiving objects:   3% (4237/141211), 772.01 KiB | 223.00Receiving objects:   3% (4883/141211), 932.01 KiB | 235.00Receiving objects:   4% (5649/141211), 932.01 KiB | 235.00Receiving objects:   4% (6660/141211), 1.27 MiB | 249.00 KReceiving objects:   5% (7061/141211), 1.27 MiB | 249.00 KReceiving objects:   5% (7705/141211), 1.43 MiB | 271.00 KReceiving objects:   6% (8473/141211), 1.54 MiB | 256.00 KReceiving objects:   6% (8606/141211), 1.62 MiB | 256.00 KReceiving objects:   6% (9062/141211), 1.68 MiB | 237.00 KReceiving objects:   6% (9792/141211), 1.83 MiB | 199.00 KReceiving objects:   7% (9885/141211), 1.83 MiB | 199.00 KReceiving objects:   7% (10837/141211), 2.04 MiB | 170.00 Receiving objects:   8% (11297/141211), 2.12 MiB | 158.00 Receiving objects:   8% (11759/141211), 2.12 MiB | 158.00 Receiving objects:   9% (12709/141211), 2.42 MiB | 172.00 Receiving objects:   9% (12978/141211), 2.42 MiB | 172.00 Receiving objects:  10% (14122/141211), 2.63 MiB | 198.00 Receiving objects:  11% (15534/141211), 2.63 MiB | 198.00 Receiving objects:  12% (16946/141211), 3.07 MiB | 285.00 Receiving objects:  12% (17808/141211), 3.07 MiB | 285.00 Receiving objects:  13% (18358/141211), 4.23 MiB | 517.00 Receiving objects:  13% (18538/141211), 4.92 MiB | 644.00 Receiving objects:  13% (19205/141211), 5.75 MiB | 804.00 Receiving objects:  14% (19770/141211), 6.64 MiB | 1020.00Receiving objects:  14% (20213/141211), 7.57 MiB | 1.17 MiReceiving objects:  15% (21182/141211), 8.43 MiB | 1.33 MiReceiving objects:  15% (21663/141211), 9.43 MiB | 1.50 MiReceiving objects:  16% (22594/141211), 10.41 MiB | 1.62 MReceiving objects:  16% (23486/141211), 11.48 MiB | 1.74 MReceiving objects:  17% (24006/141211), 11.48 MiB | 1.74 MReceiving objects:  18% (25418/141211), 13.64 MiB | 1.92 MReceiving objects:  18% (25717/141211), 13.64 MiB | 1.92 MReceiving objects:  19% (26831/141211), 15.33 MiB | 1.92 MReceiving objects:  19% (27207/141211), 15.33 MiB | 1.92 MReceiving objects:  20% (28243/141211), 16.25 MiB | 1.92 MReceiving objects:  20% (28586/141211), 17.33 MiB | 1.96 MReceiving objects:  21% (29655/141211), 18.30 MiB | 1.96 MReceiving objects:  22% (31067/141211), 19.32 MiB | 1.97 MReceiving objects:  22% (31243/141211), 19.32 MiB | 1.97 MReceiving objects:  23% (32479/141211), 20.30 MiB | 1.94 MReceiving objects:  23% (33082/141211), 21.12 MiB | 1.88 MReceiving objects:  24% (33891/141211), 22.02 MiB | 1.85 MReceiving objects:  24% (34998/141211), 22.71 MiB | 1.84 MReceiving objects:  25% (35303/141211), 22.71 MiB | 1.84 MReceiving objects:  26% (36715/141211), 23.68 MiB | 1.84 MReceiving objects:  26% (36963/141211), 24.48 MiB | 1.82 MReceiving objects:  27% (38127/141211), 25.42 MiB | 1.79 MReceiving objects:  27% (39484/141211), 26.40 MiB | 1.79 MReceiving objects:  28% (39540/141211), 26.40 MiB | 1.79 MReceiving objects:  29% (40952/141211), 27.35 MiB | 1.78 MReceiving objects:  30% (42364/141211), 28.18 MiB | 1.75 MReceiving objects:  30% (42590/141211), 28.18 MiB | 1.75 MReceiving objects:  31% (43776/141211), 29.14 MiB | 1.77 MReceiving objects:  31% (43793/141211), 29.50 MiB | 1.43 MReceiving objects:  32% (45188/141211), 29.50 MiB | 1.43 MReceiving objects:  32% (46151/141211), 31.17 MiB | 1.42 MReceiving objects:  33% (46600/141211), 31.17 MiB | 1.42 MReceiving objects:  34% (48012/141211), 31.17 MiB | 1.42 MReceiving objects:  34% (49050/141211), 31.17 MiB | 1.42 MReceiving objects:  35% (49424/141211), 32.83 MiB | 1.42 MReceiving objects:  35% (50327/141211), 32.83 MiB | 1.42 MReceiving objects:  36% (50836/141211), 32.83 MiB | 1.42 MReceiving objects:  37% (52249/141211), 34.57 MiB | 1.39 MReceiving objects:  38% (53661/141211), 34.57 MiB | 1.39 MReceiving objects:  38% (53817/141211), 34.57 MiB | 1.39 MReceiving objects:  39% (55073/141211), 35.61 MiB | 1.39 MReceiving objects:  39% (56122/141211), 36.91 MiB | 1.44 MReceiving objects:  40% (56485/141211), 36.91 MiB | 1.44 MReceiving objects:  41% (57897/141211), 36.91 MiB | 1.44 MReceiving objects:  41% (59147/141211), 38.89 MiB | 1.47 MReceiving objects:  42% (59309/141211), 38.89 MiB | 1.47 MReceiving objects:  43% (60721/141211), 38.89 MiB | 1.47 MReceiving objects:  44% (62133/141211), 39.93 MiB | 1.76 MReceiving objects:  44% (63246/141211), 40.91 MiB | 1.88 MReceiving objects:  45% (63545/141211), 40.91 MiB | 1.88 MReceiving objects:  46% (64958/141211), 41.89 MiB | 1.93 MReceiving objects:  47% (66370/141211), 42.90 MiB | 1.79 MReceiving objects:  47% (66386/141211), 42.90 MiB | 1.79 MReceiving objects:  48% (67782/141211), 42.90 MiB | 1.79 MReceiving objects:  49% (69194/141211), 43.93 MiB | 2.04 MReceiving objects:  49% (69337/141211), 44.94 MiB | 2.06 MReceiving objects:  50% (70606/141211), 45.93 MiB | 1.99 MReceiving objects:  51% (72018/141211), 45.93 MiB | 1.99 MReceiving objects:  51% (72091/141211), 46.89 MiB | 1.98 MReceiving objects:  52% (73430/141211), 47.90 MiB | 1.98 MReceiving objects:  52% (74628/141211), 48.93 MiB | 1.98 MReceiving objects:  53% (74842/141211), 48.93 MiB | 1.98 MReceiving objects:  54% (76254/141211), 49.78 MiB | 1.95 MReceiving objects:  54% (76481/141211), 50.57 MiB | 1.92 MReceiving objects:  55% (77667/141211), 50.57 MiB | 1.92 MReceiving objects:  56% (79079/141211), 51.42 MiB | 1.88 MReceiving objects:  56% (79136/141211), 52.37 MiB | 1.86 MReceiving objects:  57% (80491/141211), 53.24 MiB | 1.83 MReceiving objects:  58% (81903/141211), 53.24 MiB | 1.83 MReceiving objects:  58% (82352/141211), 54.24 MiB | 1.83 MReceiving objects:  59% (83315/141211), 54.24 MiB | 1.83 MReceiving objects:  60% (84727/141211), 55.24 MiB | 1.84 MReceiving objects:  60% (84851/141211), 55.75 MiB | 1.65 MReceiving objects:  61% (86139/141211), 56.44 MiB | 1.58 MReceiving objects:  61% (86238/141211), 56.44 MiB | 1.58 MReceiving objects:  62% (87551/141211), 56.85 MiB | 1.45 MReceiving objects:  62% (88554/141211), 57.14 MiB | 1.33 MReceiving objects:  63% (88963/141211), 57.14 MiB | 1.33 MReceiving objects:  64% (90376/141211), 57.64 MiB | 1.26 MReceiving objects:  64% (91117/141211), 58.05 MiB | 1.15 MReceiving objects:  65% (91788/141211), 58.32 MiB | 1.00 MReceiving objects:  65% (92042/141211), 58.32 MiB | 1.00 MReceiving objects:  66% (93200/141211), 59.38 MiB | 838.00Receiving objects:  67% (94612/141211), 59.38 MiB | 838.00Receiving objects:  67% (94634/141211), 59.38 MiB | 838.00Receiving objects:  68% (96024/141211), 60.86 MiB | 935.00Receiving objects:  69% (97436/141211), 60.86 MiB | 935.00Receiving objects:  69% (97927/141211), 60.86 MiB | 935.00Receiving objects:  70% (98848/141211), 61.67 MiB | 1.02 MReceiving objects:  71% (100260/141211), 62.57 MiB | 1.16 Receiving objects:  71% (100334/141211), 62.57 MiB | 1.16 Receiving objects:  72% (101672/141211), 63.36 MiB | 1.22 Receiving objects:  73% (103085/141211), 64.18 MiB | 1.31 Receiving objects:  73% (103418/141211), 64.18 MiB | 1.31 Receiving objects:  74% (104497/141211), 65.06 MiB | 1.46 Receiving objects:  75% (105909/141211), 65.06 MiB | 1.46 Receiving objects:  76% (107321/141211), 65.92 MiB | 1.56 Receiving objects:  76% (107635/141211), 65.92 MiB | 1.56 Receiving objects:  77% (108733/141211), 66.75 MiB | 1.61 Receiving objects:  78% (110145/141211), 66.75 MiB | 1.61 Receiving objects:  79% (111557/141211), 67.50 MiB | 1.60 Receiving objects:  79% (112281/141211), 67.50 MiB | 1.60 Receiving objects:  80% (112969/141211), 67.50 MiB | 1.60 Receiving objects:  81% (114381/141211), 68.36 MiB | 1.64 Receiving objects:  82% (115794/141211), 69.29 MiB | 1.67 Receiving objects:  82% (116264/141211), 69.29 MiB | 1.67 Receiving objects:  83% (117206/141211), 70.17 MiB | 1.66 Receiving objects:  84% (118618/141211), 70.82 MiB | 1.60 Receiving objects:  84% (119581/141211), 70.82 MiB | 1.60 Receiving objects:  85% (120030/141211), 70.82 MiB | 1.60 Receiving objects:  85% (121359/141211), 72.14 MiB | 1.47 Receiving objects:  86% (121442/141211), 72.14 MiB | 1.47 Receiving objects:  87% (122854/141211), 72.59 MiB | 1.38 Receiving objects:  87% (123268/141211), 73.55 MiB | 1.21 Receiving objects:  87% (123868/141211), 73.86 MiB | 1.09 Receiving objects:  88% (124266/141211), 73.86 MiB | 1.09 Receiving objects:  88% (125386/141211), 74.37 MiB | 1.01 Receiving objects:  89% (125678/141211), 74.37 MiB | 1.01 Receiving objects:  90% (127090/141211), 74.82 MiB | 943.0Receiving objects:  91% (128503/141211), 75.33 MiB | 930.0Receiving objects:  91% (128812/141211), 75.33 MiB | 930.0Receiving objects:  92% (129915/141211), 75.71 MiB | 839.0Receiving objects:  92% (130432/141211), 76.14 MiB | 858.0Receiving objects:  93% (131327/141211), 76.39 MiB | 795.0Receiving objects:  93% (131740/141211), 76.74 MiB | 741.0Receiving objects:  94% (132739/141211), 77.04 MiB | 755.0Receiving objects:  94% (133018/141211), 77.24 MiB | 705.0Receiving objects:  95% (134151/141211), 77.50 MiB | 653.0Receiving objects:  95% (134194/141211), 77.50 MiB | 653.0Receiving objects:  95% (135308/141211), 78.11 MiB | 579.0Receiving objects:  96% (135563/141211), 78.11 MiB | 579.0Receiving objects:  97% (136975/141211), 78.61 MiB | 606.0Receiving objects:  98% (138387/141211), 79.24 MiB | 645.0Receiving objects:  98% (139580/141211), 79.24 MiB | 645.0Receiving objects:  99% (139799/141211), 79.24 MiB | 645.0remote: Total 141211 (delta 135), reused 141 (delta 76), pack-reused 140952
Receiving objects: 100% (141211/141211), 79.92 MiB | 758.0Receiving objects: 100% (141211/141211), 80.41 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (103945/103945), done.
  -> Found NoWarns.patch
  -> Found QTest.patch
  -> Found dpkg.patch
  -> Found NoDocs.patch
==> Validating source files with sha256sums...
    ubuntu-ui-toolkit ... Skipped
    NoWarns.patch ... Passed
    QTest.patch ... Passed
    dpkg.patch ... Passed
    NoDocs.patch ... Passed
==> Extracting sources...
  -> Creating working copy of ubuntu-ui-toolkit git repo...
Cloning into 'ubuntu-ui-toolkit'...
done.
==> Starting prepare()...
Branch 'bionic' set up to track remote branch 'bionic' from 'origin'.
Switched to a new branch 'bionic'
patching file .qmake.conf
patching file tests/unit/deprecated_theme_engine/tst_deprecated_theme_engine.cpp
Hunk #1 FAILED at 56.
1 out of 1 hunk FAILED -- saving rejects to file tests/unit/deprecated_theme_engine/tst_deprecated_theme_engine.cpp.rej
patching file tests/unit/inversemousearea/tst_inversemouseareatest.cpp
Hunk #1 FAILED at 97.
Hunk #2 FAILED at 110.
Hunk #3 FAILED at 119.
Hunk #4 FAILED at 134.
Hunk #5 FAILED at 143.
Hunk #6 FAILED at 161.
Hunk #7 FAILED at 169.
Hunk #8 FAILED at 177.
Hunk #9 FAILED at 185.
Hunk #10 FAILED at 210.
Hunk #11 FAILED at 253.
11 out of 11 hunks FAILED -- saving rejects to file tests/unit/inversemousearea/tst_inversemouseareatest.cpp.rej
patching file tests/unit/mainview11/tst_mainview.cpp
Hunk #1 FAILED at 57.
1 out of 1 hunk FAILED -- saving rejects to file tests/unit/mainview11/tst_mainview.cpp.rej
patching file tests/unit/mainview13/tst_mainview.cpp
Hunk #1 FAILED at 57.
1 out of 1 hunk FAILED -- saving rejects to file tests/unit/mainview13/tst_mainview.cpp.rej
patching file tests/unit/mousefilters/tst_mousefilterstest.cpp
Hunk #1 FAILED at 146.
Hunk #2 FAILED at 175.
Hunk #3 FAILED at 204.
Hunk #4 FAILED at 234.
Hunk #5 FAILED at 265.
Hunk #6 FAILED at 296.
Hunk #7 FAILED at 327.
Hunk #8 FAILED at 358.
Hunk #9 FAILED at 395.
Hunk #10 FAILED at 432.
Hunk #11 FAILED at 464.
Hunk #12 FAILED at 496.
Hunk #13 FAILED at 519.
Hunk #14 FAILED at 536.
Hunk #15 FAILED at 556.
Hunk #16 FAILED at 600.
Hunk #17 FAILED at 631.
Hunk #18 FAILED at 663.
Hunk #19 FAILED at 694.
Hunk #20 FAILED at 725.
Hunk #21 FAILED at 756.
Hunk #22 FAILED at 780.
Hunk #23 FAILED at 807.
Hunk #24 FAILED at 843.
Hunk #25 FAILED at 883.
Hunk #26 FAILED at 913.
Hunk #27 FAILED at 921.
Hunk #28 FAILED at 1005.
Hunk #29 FAILED at 1020.
Hunk #30 FAILED at 1029.
Hunk #31 FAILED at 1038.
Hunk #32 FAILED at 1046.
Hunk #33 FAILED at 1104.
Hunk #34 FAILED at 1133.
Hunk #35 FAILED at 1162.
Hunk #36 FAILED at 1173.
Hunk #37 FAILED at 1199.
Hunk #38 FAILED at 1232.
38 out of 38 hunks FAILED -- saving rejects to file tests/unit/mousefilters/tst_mousefilterstest.cpp.rej
patching file tests/unit/performance/tst_performance.cpp
Hunk #1 FAILED at 35.
1 out of 1 hunk FAILED -- saving rejects to file tests/unit/performance/tst_performance.cpp.rej
patching file tests/unit/statesaver/tst_statesaver.cpp
Hunk #1 FAILED at 458.
1 out of 1 hunk FAILED -- saving rejects to file tests/unit/statesaver/tst_statesaver.cpp.rej
patching file tests/unit/subtheming/tst_subtheming.cpp
Hunk #1 FAILED at 739.
1 out of 1 hunk FAILED -- saving rejects to file tests/unit/subtheming/tst_subtheming.cpp.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
[noire@Austcools-MacBook-Pro ubuntu-ui-toolkit-git]$```

**Comment by vanyasem** [comment] 2019-02-13 03:52
It was probably upstreamed by Rodney since I last rebuilt the project, you can safely remove the patch from the PKGBUILD

**Comment by vanyasem** [comment] 2019-02-13 03:56
See https://github.com/ubports/ubuntu-ui-toolkit/issues/9 and https://github.com/ubports/ubuntu-ui-toolkit/issues/12

**Comment by Austcool-Walker** [comment] 2019-02-13 13:50
```[noire@Austcools-MacBook-Pro ubuntu-ui-toolkit-git]$ makepkg
==> Making package: ubuntu-ui-toolkit-git r18022.f07ae3d6d-1 (Wed 13 Feb 2019 08:49:49 AM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating ubuntu-ui-toolkit git repo...
Fetching origin
  -> Found NoWarns.patch
  -> Found QTest.patch
  -> Found dpkg.patch
  -> Found NoDocs.patch
  -> Found adapters.patch
==> ERROR: Integrity checks (sha256) differ in size from the source array.
[noire@Austcools-MacBook-Pro ubuntu-ui-toolkit-git]$ makepkg --skipinteg
==> Making package: ubuntu-ui-toolkit-git r18022.f07ae3d6d-1 (Wed 13 Feb 2019 08:50:07 AM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating ubuntu-ui-toolkit git repo...
Fetching origin
  -> Found NoWarns.patch
  -> Found QTest.patch
  -> Found dpkg.patch
  -> Found NoDocs.patch
  -> Found adapters.patch
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Creating working copy of ubuntu-ui-toolkit git repo...
Switched to and reset branch 'makepkg'
==> Starting prepare()...
Branch 'bionic' set up to track remote branch 'bionic' from 'origin'.
Switched to a new branch 'bionic'
==> Starting pkgver()...
==> Updated version: ubuntu-ui-toolkit-git r18021.cee7f49f4-1
==> Removing existing $pkgdir/ directory...
==> Starting build()...
cd src/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/src/ubuntu-ui-toolkit/src/src.pro ) && make -f Makefile 
make[1]: Entering directory '/home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/src/ubuntu-ui-toolkit/src'
cd UbuntuGestures/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/src/ubuntu-ui-toolkit/src/UbuntuGestures/UbuntuGestures.pro ) && make -f Makefile 
make[2]: Entering directory '/home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/src/ubuntu-ui-toolkit/src/UbuntuGestures'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/src/ubuntu-ui-toolkit/src/UbuntuGestures'
cd UbuntuMetrics/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/src/ubuntu-ui-toolkit/src/UbuntuMetrics/UbuntuMetrics.pro ) && make -f Makefile 
make[2]: Entering directory '/home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/src/ubuntu-ui-toolkit/src/UbuntuMetrics'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/src/ubuntu-ui-toolkit/src/UbuntuMetrics'
cd UbuntuToolkit/ && ( test -e Makefile || /usr/bin/qmake -o Makefile /home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/src/ubuntu-ui-toolkit/src/UbuntuToolkit/UbuntuToolkit.pro ) && make -f Makefile 
make[2]: Entering directory '/home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/src/ubuntu-ui-toolkit/src/UbuntuToolkit'
g++ -c -include .pch/UbuntuToolkit -fstack-protector -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -pthread -fno-exceptions -Wall -W -Wdate-time -Wformat -Werror=format-security -Wsuggest-override -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Werror -Wno-error=cpp -Wno-error=deprecated-declarations -Wno-error=strict-overflow -Wno-error=implicit-fallthrough -D_REENTRANT -fPIC -DUBUNTUTOOLKIT_NO_NAMESPACE -DUBUNTUTOOLKIT_ENABLE_X11_TOUCH_EMULATION -D_FORTIFY_SOURCE=2 -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_UBUNTUTOOLKIT_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_UBUNTUGESTURES_LIB -DQT_UBUNTUMETRICS_LIB -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_SYSTEMINFO_LIB -DQT_NETWORK_LIB -DQT_TESTLIB_LIB -DQT_DBUS_LIB -DQT_ORGANIZER_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/src/ubuntu-ui-toolkit/src/UbuntuToolkit"' -I. -I../../include -I../../include/UbuntuToolkit -I../../include/UbuntuToolkit/5.5.0 -I../../include/UbuntuToolkit/5.5.0/UbuntuToolkit -isystem /usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/uuid -isystem /usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I../../include/UbuntuGestures/5.5.0 -I../../include/UbuntuGestures/5.5.0/UbuntuGestures -I../../include/UbuntuGestures -I../../include/UbuntuMetrics -isystem /usr/include/qt/QtQuick/5.12.0 -isystem /usr/include/qt/QtQuick/5.12.0/QtQuick -isystem /usr/include/qt/QtGui/5.12.0 -isystem /usr/include/qt/QtGui/5.12.0/QtGui -isystem /usr/include/qt/QtQml/5.12.0 -isystem /usr/include/qt/QtQml/5.12.0/QtQml -isystem /usr/include/qt/QtCore/5.12.0 -isystem /usr/include/qt/QtCore/5.12.0/QtCore -isystem /usr/include/qt -isystem /usr/include/qt/QtQuick -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtQml -isystem /usr/include/qt/QtSystemInfo/5.4.0 -isystem /usr/include/qt/QtSystemInfo/5.4.0/QtSystemInfo -isystem /usr/include/qt/QtSystemInfo -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtTest -isystem /usr/include/qt/QtDBus -isystem /usr/include/qt/QtOrganizer -isystem /usr/include/qt/QtCore -I.moc -isystem /usr/include/libdrm -I/usr/lib/qt/mkspecs/linux-g++ -o .obj/alarmsadapter_organizer.o adapters/alarmsadapter_organizer.cpp
adapters/alarmsadapter_organizer.cpp: In constructor ‘AlarmsAdapter::AlarmsAdapter(AlarmManager*)’:
adapters/alarmsadapter_organizer.cpp:423:55: error: ‘class QtOrganizer::QOrganizerManager’ has no member named ‘defaultCollectionId’; did you mean ‘defaultCollection’?
     collection = manager->collection(manager->defaultCollectionId());
                                               ^~~~~~~~~~~~~~~~~~~
                                               defaultCollection
make[2]: *** [Makefile:2133: .obj/alarmsadapter_organizer.o] Error 1
make[2]: Leaving directory '/home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/src/ubuntu-ui-toolkit/src/UbuntuToolkit'
make[1]: *** [Makefile:104: sub-toolkit-lib-make_first] Error 2
make[1]: Leaving directory '/home/noire/Desktop/Unity8-Arch/ubuntu-ui-toolkit-git/src/ubuntu-ui-toolkit/src'
make: *** [Makefile:52: sub-src-make_first] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by Austcool-Walker** [comment] 2019-02-13 13:52
looks like a `defaultCollectionnId` patch is needed

**Comment by vanyasem** [comment] 2019-02-13 16:42
no, the issue is that i packaged old qtpim in this repo for the sake of compatibility. you first need to install newer qtpim, and then try to build this package @Austcool-Walker 

sorry for the confusion

**Comment by Austcool-Walker** [comment] 2019-02-13 21:33
thanks will try :+1:

**Comment by Austcool-Walker** [comment] 2019-02-14 23:32
I tried got newer errors instead of making it all the way though the build

**Comment by vanyasem** [comment] 2019-02-15 00:45
@Austcool-Walker well that's a shame, but was supposed to happen. At the very least you should report them, and if you're experienced enough, you might try to patch them. Thanks !

**Comment by vanyasem** [comment] 2019-02-23 15:27
See #7 for a possible fix

**Comment by vanyasem** [comment] 2019-11-20 20:37
Closed in https://github.com/vanyasem/Unity8-Arch/commit/98752ad406abe078c677075a2f47ff85d0d8af46

**Closed by vanyasem** 2019-11-20 20:37 UTC
